import type { IntakeRequest, Room } from "./types";

export const initialRooms: Room[] = [
  {
    id: "101",
    wing: "East Wing",
    beds: [
      { index: 0, occupied: true, patientName: "M. Torres" },
      { index: 1, occupied: true, patientName: "J. Rivera" },
      { index: 2, occupied: true, patientName: "A. Chen" },
      { index: 3, occupied: false },
    ],
  },
  {
    id: "102",
    wing: "East Wing",
    beds: [
      { index: 0, occupied: true, patientName: "R. Patel" },
      { index: 1, occupied: true, patientName: "L. Santos" },
      { index: 2, occupied: true, patientName: "K. Johnson" },
      { index: 3, occupied: true, patientName: "D. Williams" },
    ],
  },
  {
    id: "103",
    wing: "West Wing",
    beds: [
      { index: 0, occupied: true, patientName: "S. Martinez" },
      { index: 1, occupied: true, patientName: "T. Brown" },
      { index: 2, occupied: false },
    ],
  },
  {
    id: "201",
    wing: "North Wing",
    beds: [
      { index: 0, occupied: true, patientName: "E. Garcia" },
      { index: 1, occupied: false },
      { index: 2, occupied: false },
      { index: 3, occupied: false },
    ],
  },
  {
    id: "202",
    wing: "West Wing",
    beds: [
      { index: 0, occupied: true, patientName: "B. Wilson" },
      { index: 1, occupied: true, patientName: "N. Anderson" },
      { index: 2, occupied: true, patientName: "C. Taylor" },
    ],
  },
  {
    id: "203",
    wing: "North Wing",
    beds: [
      { index: 0, occupied: true, patientName: "H. Thomas" },
      { index: 1, occupied: true, patientName: "P. Jackson" },
      { index: 2, occupied: false },
      { index: 3, occupied: false },
    ],
  },
];

export const initialIntakes: IntakeRequest[] = [
  {
    id: "intake-001",
    name: "Marcus D.",
    initials: "MD",
    dob: "May 3, 1989",
    phone: "(555) 234-5678",
    emergencyContact: {
      name: "Sarah D.",
      phone: "(555) 234-1111",
      relationship: "Sister",
    },
    insurance: {
      provider: "Blue Cross",
      planType: "PPO",
      memberId: "BCB-4821-22",
      authStatus: "pending",
    },
    program: "Residential Detox",
    admittingReason:
      "Alcohol dependency with elevated withdrawal risk. Reports drinking 8–10 drinks daily for the past 6 months.",
    substances: ["Alcohol", "Benzodiazepines"],
    lastUseDate: "Mar 13, 2026",
    medicalFlags: ["Withdrawal Risk", "Hypertension"],
    referralType: "doctor",
    referringSource: "Dr. James Patel, MD — Internal Medicine",
    requestDate: "Mar 14, 2026",
    priority: "high",
    status: "pending",
  },
  {
    id: "intake-002",
    name: "Sofia R.",
    initials: "SR",
    dob: "Nov 18, 1995",
    phone: "(555) 876-4321",
    emergencyContact: {
      name: "Carmen R.",
      phone: "(555) 876-0001",
      relationship: "Mother",
    },
    insurance: {
      provider: "Medicaid",
      planType: "HMO",
      memberId: "MCD-8823-99",
      authStatus: "approved",
    },
    program: "30-Day Residential",
    admittingReason:
      "Opioid dependency, seeking long-term residential treatment. Stable vitals, no acute withdrawal at time of referral.",
    substances: ["Opioids (Fentanyl)"],
    lastUseDate: "Mar 12, 2026",
    medicalFlags: [],
    referralType: "hotline",
    referringSource: "SAMHSA National Helpline",
    requestDate: "Mar 13, 2026",
    priority: "normal",
    status: "pending",
  },
  {
    id: "intake-003",
    name: "James T.",
    initials: "JT",
    dob: "Aug 22, 1980",
    phone: "(555) 311-9988",
    emergencyContact: {
      name: "Linda T.",
      phone: "(555) 311-0055",
      relationship: "Spouse",
    },
    insurance: {
      provider: "Aetna",
      planType: "PPO",
      memberId: "ATN-7744-56",
      authStatus: "approved",
    },
    program: "Medical Detox",
    admittingReason:
      "Methamphetamine dependency. Patient is in early withdrawal. Medically supervised detox recommended.",
    substances: ["Methamphetamine"],
    lastUseDate: "Mar 11, 2026",
    medicalFlags: ["Cardiac Monitoring Needed"],
    referralType: "family",
    referringSource: "Self-referred via family intervention",
    requestDate: "Mar 12, 2026",
    priority: "normal",
    status: "pending",
  },
  {
    id: "intake-004",
    name: "Elena V.",
    initials: "EV",
    dob: "Feb 14, 1998",
    phone: "(555) 420-6677",
    emergencyContact: {
      name: "Marco V.",
      phone: "(555) 420-6600",
      relationship: "Father",
    },
    insurance: {
      provider: "United Healthcare",
      planType: "EPO",
      memberId: "UHC-3310-44",
      authStatus: "denied",
    },
    program: "28-Day Residential",
    admittingReason:
      "Alcohol and cannabis polysubstance use. Seeking voluntary residential treatment. No acute medical concerns.",
    substances: ["Alcohol", "Cannabis"],
    lastUseDate: "Mar 10, 2026",
    medicalFlags: [],
    referralType: "self",
    referringSource: "Self-referred via contigoU platform",
    requestDate: "Mar 11, 2026",
    priority: "normal",
    status: "pending",
  },
  {
    id: "intake-005",
    name: "Carlos M.",
    initials: "CM",
    dob: "Oct 7, 1975",
    phone: "(555) 991-2233",
    emergencyContact: {
      name: "Rosa M.",
      phone: "(555) 991-2200",
      relationship: "Wife",
    },
    insurance: {
      provider: "Cigna",
      planType: "PPO",
      memberId: "CIG-6622-11",
      authStatus: "pending",
    },
    program: "Medical Detox",
    admittingReason:
      "Severe alcohol withdrawal. Patient reporting tremors, diaphoresis, and insomnia. Immediate medical supervision required.",
    substances: ["Alcohol"],
    lastUseDate: "Mar 14, 2026",
    medicalFlags: ["Severe Withdrawal", "Seizure Risk", "IV Monitoring Required"],
    referralType: "doctor",
    referringSource:
      "Dr. Angela Reyes, MD — Emergency Medicine, St. Luke's Hospital",
    requestDate: "Mar 15, 2026",
    priority: "high",
    status: "pending",
  },
];
